name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.3.1
      with:
        path: 'src'

