name: Build and Deploy
on: 
  push:
    tags:
    - '*'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 0  # need this for all history for all branches and tags
    - name: Building
      run: yarn && yarn build
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        filename: 'release.zip'
        path: 'build'
    - name: LS
      run: ls
    - name: Upload Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "release.zip"
        token: ${{ secrets.TOKEN }}
